Repository joostlek/python-mealie, pull requests merged in 2024-06, with the labels that each got.

#148 Reformat openapi.json
  openapi.json
Labels: maintenance

#149 Update openapi
  openapi.json
Labels: maintenance

#150 Add mealplan date
  src/aiomealie/models.py
  tests/__snapshots__/test_mealie.ambr
Labels: new-feature

#151 Improve all
  README.md
  src/aiomealie/__init__.py
Labels: maintenance

#152 Add token authentication
  src/aiomealie/__init__.py
  src/aiomealie/exceptions.py
  src/aiomealie/mealie.py
Labels: new-feature

#153 Recipe can be nullable
  src/aiomealie/models.py
Labels: bugfix

#161 Add support for custom port
  src/aiomealie/mealie.py
  tests/conftest.py
  tests/test_mealie.py
Labels: new-feature

#162 Add support for any url
  src/aiomealie/mealie.py
  tests/conftest.py
  tests/const.py
  tests/test_mealie.py
Labels: new-feature

#166 Add methods to fetch group, shopping list and their items
  src/aiomealie/__init__.py
  src/aiomealie/mealie.py
  src/aiomealie/models.py
  tests/__snapshots__/test_mealie.ambr
  tests/conftest.py
  tests/fixtures/groups_self.json
  tests/fixtures/shopping_items.json
  tests/fixtures/shopping_lists.json
  tests/test_mealie.py
Labels: new-feature

#171 Support mealplan notes
  src/aiomealie/models.py
  tests/__snapshots__/test_mealie.ambr
  tests/fixtures/mealplans.json
Labels: new-feature

#168 Add, Update and Delete shopping items
  src/aiomealie/exceptions.py
  src/aiomealie/mealie.py
  src/aiomealie/models.py
  tests/fixtures/authentication_error.json
  tests/fixtures/validation_error.json
  tests/test_mealie.py
Labels: new-feature

#172 Add support for fetching userdata
  src/aiomealie/__init__.py
  src/aiomealie/mealie.py
  src/aiomealie/models.py
  tests/__snapshots__/test_mealie.ambr
  tests/fixtures/users_self.json
  tests/test_mealie.py
Labels: new-feature

#173 Use ORJSONDecoder for decoding a list
  src/aiomealie/mealie.py
Labels: enhancement

#175 Add method for fetching single recipe
  src/aiomealie/__init__.py
  src/aiomealie/exceptions.py
  src/aiomealie/mealie.py
  src/aiomealie/models.py
  tests/__snapshots__/test_mealie.ambr
  tests/fixtures/not_found_error.json
  tests/fixtures/recipe.json
  tests/test_mealie.py
Labels: new-feature

#176 Expose ShoppingList and ShoppingItem
  src/aiomealie/__init__.py
Labels: enhancement

#177 Add method for importing recipe via URL
  src/aiomealie/__init__.py
  src/aiomealie/exceptions.py
  src/aiomealie/mealie.py
  tests/__snapshots__/test_mealie.ambr
  tests/fixtures/bad_request_error.json
  tests/fixtures/scrape_recipe.json
  tests/test_mealie.py
Labels: new-feature

#178 Expose MutateShoppingItem
  src/aiomealie/__init__.py
Labels: bugfix
